AWS_ACCESS_KEY_ID: ""
AWS_SECRET_ACCESS_KEY: ""
AWS_REGION: "us-west-2"
AWS_BUCKET: "winnitron"
POSTMARK_API_TOKEN: ""
GOOGLE_ANALYTICS_TRACKING_ID: ""
GOOGLE_MAPS_API_KEY: ""
TWITTER_CONSUMER_KEY: ""
TWITTER_CONSUMER_SECRET: ""
REDIS_URL: "redis://localhost:6379/1"
ADMIN_EMAIL: "susan@example.com"
INLINE_SIDEKIQ: "yep"