default: &default
  "1":
    up: "Up"
    down: "Down"
    right: "Right"
    left: "Left"
    button"1": "/"
    button"2": "."

  "2":
    up: "w"
    down: "s"
    right: "d"
    left: "a"
    button"1": "`"
    button"2": "1"

  "3":
    up: "i"
    down: "k"
    right: "l"
    left: "j"
    button"1": "g"
    button"2": "h"

  "4":
    up: "Numpad8"
    down: "Numpad5"
    right: "Numpad6"
    left: "Numpad4"
    button"1": "Numpad1"
    button"2": "Numpad2"

legacy: &legacy
  <<: *default

  "1":
    up: "Up"
    down: "Down"
    right: "Right"
    left: "Left"
    button"1": "x"
    button"2": "z"

  "2":
    up: "i"
    down: "k"
    right: "l"
    left: "j"
    button"1": "n"
    button"2": "m"

flash:
  <<: *legacy

pico8:
  <<: *default

  "1":
    up: "Up"
    down: "Down"
    right: "Right"
    left: "Left"
    button"1": "m"
    button"2": "n"

  "2":
    up: "e"
    down: "d"
    right: "f"
    left: "s"
    button"1": "q"
    button"2": "w"
